In [2]:
k = 10
x = 5

Q = [[3]*k]*x

print(Q)

[[3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3], [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]]


In [3]:
import numpy as np
Q = np.ones((5, 10))*5

print(Q)

[[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]]


In [4]:
Q = Q + 5

print(Q)

[[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]
 [10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]]


In [5]:
s = np.array([3,42,11,2,3,5,6])
x = np.argmax(1/s)
print(x)

3


In [6]:
c = 2 # degree of exploration
sq_term = np.sqrt((np.log(t)/N_values[i]))
act = np.argmax(Q_values[i]+c*sq_term)

NameError: name 't' is not defined

In [23]:
import numpy as np
probs = [.3, .2, .3, .4]

for _ in range(100):
    for i in range(4):
        if np.random.random() < probs[i]:
            print(i)
            break
        if (i==3):
            print('nothing selected')
    

nothing selected
nothing selected
3
3
nothing selected
2
nothing selected
0
3
2
nothing selected
0
2
2
nothing selected
2
0
0
3
2
2
2
nothing selected
0
nothing selected
1
0
2
1
3
nothing selected
0
1
nothing selected
3
2
3
nothing selected
nothing selected
0
nothing selected
0
3
2
0
2
1
0
nothing selected
nothing selected
1
0
3
2
nothing selected
0
2
0
2
nothing selected
1
3
0
2
0
0
3
2
2
0
nothing selected
nothing selected
nothing selected
2
2
1
3
nothing selected
nothing selected
2
2
2
nothing selected
1
nothing selected
nothing selected
1
2
3
2
nothing selected
2
nothing selected
0
0
0
0
3
nothing selected
2


In [39]:
import numpy as np
n_bandits = 4
k = 10

H = np.ones((n_bandits, k)) * np.random.randint(k)
print(H)

[[9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [40]:
x = H[1][2]
y = H[1,2]

print(x,y)

9.0 9.0


In [1]:
x = [1,2,3,4,5,2,4,2]
y = x[::-1]
print(y)

w1 = x[:2]
w2 = x[3:]

print(w1,w2)



[2, 4, 2, 5, 4, 3, 2, 1]
[1, 2] [4, 5, 2, 4, 2]


In [3]:
x[1:5]

[2, 3, 4, 5]